version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:z
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin123"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge

volumes:
  pgdata: